name: CI/CD Pipeline

# Указываем триггеры: при пуше в ветку main и создании pull request'ов
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # # Шаг 3: Установка зависимостей
      # - name: Install dependencies
      #   run: go mod download

      # # Шаг 4: Сборка Go-приложения
      # - name: Build the Go app
      #   run: go build -o myapp .

      # Шаг 5: Логинимся в Docker Hub (если используем Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 6: Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Шаг 7: Публикация Docker-образа в Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker tag myapp:latest srg206/myapp:latest && docker push srg206/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull srg206/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 8000:8000 srg206/myapp:latest
